---

- name: Provision the jail
  connection: ssh
  gather_facts: false
  hosts: jailhosts
  user: jenkins-deploy
  roles:
    - provision-jail

- name: Install 2016-site
  connection: ssh
  gather_facts: false
  hosts: jails
  user: root
  roles:
    - 2016-site

- name: Cleanup the jail
  connection: ssh
  gather_facts: false
  hosts: jailhosts
  user: jenkins-deploy
  roles:
    - provision-jail-cleanup
